<script setup lang="ts">
import {ref,computed,watch} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {type Page} from './catalog'
import {downloadDemo,state,persist} from './store'
const props=defineProps<{page:Page,row:any,tab:string,persona:string}>();const emit=defineEmits(['navigate','action'])
const checked=ref(['适用剧本','实际阵容','节目单','精选照片','全场录像']),version=ref('V3'),position=ref(28),playing=ref(false),zoom=ref(100),mediaTab=ref('视频'),purpose=ref('剧院巡演宣传'),reviewNote=ref(''),publicView=ref(false),locked=ref(false),paragraph=ref('2026年，院团持续推进原创作品《春江月》的巡演与艺术交流。本节依据已确认演出档案整理，场次统计以唯一场次编号去重。'),chapter=ref('年度概况')
const draftKey=computed(()=>props.page.id+':'+props.row.id+':'+props.tab)
watch(draftKey,()=>{paragraph.value=state.drafts[draftKey.value]?.paragraph||paragraph.value;locked.value=!!state.drafts[draftKey.value]?.locked})
const isHistory=computed(()=>/记录|历史|日志|变更|流水|版本与回退/.test(props.tab))
const genericRows=computed(()=>{
 const k=props.page.id+':'+props.tab
 const map:Record<string,string[][]>={
 'editions:角色与岗位':[['主角','演员角色','计划：演员甲 / 实际：演员乙'],['舞台监督','工作人员','刘执行']],
 'people:实际参演':[['广州首演','主角 / 已确认','2026-10-08'],['深圳巡演','替补 / 已确认','2026-09-20']],
 'people:计划参与':[['秋日艺术季','演员甲 / 待演出','2026-10-18']],
 'people:合并记录':[['同名人员候选','需要人工核验','旧ID保留重定向']],
 'venues:厅室与座位':[['大剧场','基础800座','本场开放800 / 可售750'],['小剧场','基础300座','各场独立维护']],
 'venues:技术资料':[['舞台平面图','V2 / 已确认','内部'],['灯光回路表','V1 / 待更新','内部']],
 'projects:场次日历':[['10月08日 19:30','广州首演','已完成'],['10月18日 19:30','开幕晚会','已排定']],
 'projects:项目成员':[['陈项目','项目负责人','2026-12-31到期'],['周宣传','宣传资料预览与申请分享','禁止财务字段']],
 'collections:资料清单':[['谢幕精选照片','V1 / 10张','宣传授权已确认'],['60秒宣传片','V2','已批准代理预览']],
 'recognition:预算预览':[['OCR','24页 × 演示单价','预计¥0.48'],['队列','前方3个任务','超额进入审批']],
 'recognition:部分失败':[['第3页','图像损坏','可逐页重试'],['第12页','低置信度','需人工校订']],
 'collection-tasks:投稿清单':[['摄影工作室 / 谢幕照片','120张 / 2.8GB','待审核'],['录像团队 / A机位','26.4GB','检查中']],
 'collection-tasks:隔离收件区':[['未知工程包.zip','检查失败','不可预览 / 需重新提交']],
 'collection-tasks:待审核':[['摄影工作室 / 谢幕照片','摄影授权待补齐','接收前核对重复关系']],
 'collection-tasks:退回补充':[['海报源文件','缺作者声明','等待本人补交']],
 'users:部门组织':[['院团','话剧部 / 宣传部 / 档案室','组织结构示意'],['外部合作方','独立账号组','不自动进入内部组织']],
 'users:离岗交接':[['待转交档案','12条','原上传人事实保留'],['待暂停外链','2条','业务负责人审核接管']],
 'users:临时授权':[['秋季巡演项目','预览 / 上传','2026-12-31自动到期']],
 'permissions:业务范围':[['2026秋季巡演','指定项目','仅本角色允许动作'],['广州首演','指定场次','资料级限制优先']],
 'permissions:字段限制':[['联系方式','默认受限','单独授权'],['财务金额','显式拒绝','导出同样隐藏']],
 'permissions:影响预览':[['受影响账号','3个演示账号','权限收紧立即生效'],['现有分享','2条演示链接','需重新审核']],
 'dictionaries:新增建议':[['舞台监督提示本','刘执行提交','待档案管理员审核']],
 'dictionaries:合并记录':[['演出录像 → 全场实录','42条历史引用','保留旧值映射']],
 'templates:审批节点':[['项目负责人','内容及用途审核','申请人不可自审'],['权利负责人','权利范围核对','无审批人进入待分配']],
 'templates:归档清单':[['剧本 / 实际阵容 / 节目单','必交','演后3个工作日'],['录像 / 照片 / 结算','按演出性质配置','豁免需理由及审批']],
 'templates:到期提醒':[['资料提交','演后3个工作日','责任人站内待办'],['归档检查','演后10个工作日','档案管理员']],
 'identity:账号绑定':[['外部稳定ID: staff-008','林档案','已匹配'],['外部稳定ID: staff-012','同名候选2人','待人工核验']],
 'identity:组织映射':[['archive-team','档案管理员 / 指定库','变更需审批'],['finance-team','不自动授予财务权限','人工确认']],
 'identity:应急访问':[['保管人甲 / 保管人乙','多因素验证','需审批后限定时长启用'],['业务内容','默认不可读','紧急运维不等于数据权限']],
 'channels:场次映射':[['外部EVT-188','广州首演 / 内部EV-008','待审批'],['外部EVT-199','无明确匹配','不能按同名自动关联']],
 'channels:异常处理':[['同步超时','最后游标EV-182','重试保持幂等'],['乱序更正','来源版本不明确','挂起人工核对']],
 'storage:策略与候选':[['2024巡演机位 / 2.4TB','180天未实际访问','无保全 / 待批准'],['首演照片 / 38GB','活跃分享引用','排除迁移']],
 'storage:取回申请':[['2024巡演A机位','预计2小时 / 演示¥24','热副本保留7天'],['同源另一个申请','共享物理任务','领取权限独立检查']],
 'storage:引用保护':[['活跃原件下载分享','到期2026-10-16','固定热副本'],['内部保全','保全期内','禁止自动迁移']],
 'backups:备份计划':[['元数据','每小时 / RPO目标1小时','独立故障域'],['原件','每日 / RPO目标24小时','至少一份离线或不可变副本']],
 'backups:恢复演练':[['指定场次全量恢复','元数据 / 文件 / 版本 / 权限','隔离目标'],['历史分享','恢复后全部暂停','复核撤销与到期后开放']],
 'backups:可迁出清单':[['业务关系及稳定ID','CSV / JSON','包含权限与权利'],['原件与衍生件','版本映射 / 哈希清单','可重建场次档案']],
 'audit:服务监控':[['业务API / 文件网关','演示：正常','响应与访问分队列'],['转码队列','演示：12个等待','可限并发'],['主存储','演示：85%','触发告警']],
 'budgets:预占与结算':[['转写任务ASR-002','预占42分钟','按实际结算'],['失败重试','仍记录用量','不假定服务商免计费']],
 'budgets:资源队列':[['交互查询','优先级高','独立资源池'],['历史批量识别','并发2','不阻塞在线分享']],
 'models:词表':[['春江月','剧名','人工确认'],['青禾','艺名','已关联人员档案'],['追光','专业术语','舞台技术']],
 'models:质量评估':[['语义检索冻结集','120题 / 尚未执行','目标Recall@10≥85%'],['问答冻结集','150题 + 权限攻击集','尚未验收'],['引用有效率','要求100%','必须人工复核']],
 'models:派生清理':[['源资料 → OCR → 索引','撤权立即拒访','物理清理任务待执行'],['源片 → 选段 → 分享','暂停新访问','保留依赖与处理依据']],
 'models:用户反馈':[['识别错误','剧名识别不准确','待指派'],['引用错误','页码定位偏移','待复核']],
 'settings:保存与清理':[['回收站','90天','保全除外'],['临时导出包','24小时','领取时重新鉴权'],['审计日志','24个月','按院团制度配置']],
 'settings:通知与验证':[['站内待办','按事项合并提醒','启用'],['邮箱验证码','等待通道配置','失败不匿名放行']],
 'settings:安全策略':[['敏感审批','多因素验证','重新验证失败则拒绝'],['原件与衍生件','私有访问','不公开存储永久地址']]
 }
 return map[k]|| (isHistory.value?[['2026-10-09 09:30','林档案','修改资料说明 · 保留旧值'],['2026-10-08 17:20','陈项目','提交审核 · 演示记录']]:props.page.fields.slice(0,8).map((f,i)=>[f.label,String(props.row.form?.[f.key]??(i===0?props.row.title:f.options?.[0]||'待补充')),f.type==='password'?'凭证只用于配置，不展示':'可通过编辑信息修改']))
})
function saveParagraph(){state.drafts[draftKey.value]={paragraph:paragraph.value,locked:locked.value};persist();ElMessage.success('编纂演示稿已保存')}
function regenerate(){if(locked.value){ElMessage.warning('此段已人工锁定，不会被重生成覆盖');return}paragraph.value='【演示初稿】院团围绕《春江月》开展创作及巡演。本段仅使用示例档案，统计与艺术成果需由业务负责人核对，未核验荣誉不纳入正式材料。';saveParagraph()}
async function confirm(label:string){try{await ElMessageBox.confirm(`${label}？仅保存本页演示状态。`,label);ElMessage.success('已记录演示操作')}catch{}}
</script>
<template>
<div class="detail-panels">
 <template v-if="page.id==='assets'&&tab==='预览'"><div class="media-controls"><el-radio-group v-model="mediaTab"><el-radio-button v-for="t in ['视频','文档','照片','音频','不支持格式']" :key="t" :value="t">{{t}}</el-radio-button></el-radio-group><el-select v-model="version" aria-label="预览版本" style="width:100px"><el-option v-for="v in ['V3','V2','V1']" :key="v" :value="v"/></el-select></div><div v-if="['视频','照片','音频'].includes(mediaTab)" class="media-stage" :class="{photo:mediaTab==='照片'}"><div class="stage-light one"></div><div class="stage-light two"></div><span class="media-watermark">接收人：演示账号 · {{version}} · 2026-10-09</span><h2>春江月</h2><p>{{mediaTab}}预览示意 · 未载入真实媒体</p><button class="play-control" @click="playing=!playing">{{playing?'Ⅱ':'▶'}}</button></div><div v-else-if="mediaTab==='文档'" class="document-page"><small>剧本文稿 · {{version}} · 预览示意</small><h2>春江月</h2><h3>第二幕 · 月上柳梢</h3><p>【灯光渐亮。月色映在窗前，远处传来渡船的声音。】</p><p>甲：这条河，记得每一个归来的人。</p><p>乙：那就让我们，再等一盏灯。</p><div class="document-lines"></div><small>演示文本 · 第12页 / 共48页</small></div><el-empty v-else description="此工程格式暂不支持预览，可补充人工预览图。"/><div class="media-controls"><el-slider v-model="position" :show-tooltip="true"/><span>{{position}} / 100</span><el-select model-value="1.0×" style="width:100px" aria-label="播放速度"><el-option v-for="r in ['0.5×','1.0×','1.5×','2.0×']" :key="r" :value="r"/></el-select><el-select model-value="720p" style="width:100px" aria-label="清晰度"><el-option value="720p"/><el-option value="1080p"/></el-select></div><p class="muted">当前 {{version}}；归档 V2。预览与原件独立，水印不等于防截图或防录屏。</p></template>
 <template v-else-if="page.id==='assets'&&tab==='文件版本'"><el-alert title="当前版本V3，正式归档版本V2。旧分享固定旧版本，不自动切换。" :closable="false"/><el-table :data="[{v:'V3',note:'补充谢幕片段',by:'赵影像',state:'当前版本'},{v:'V2',note:'归档定稿',by:'林档案',state:'归档版本 · 2条分享引用'},{v:'V1',note:'首次上传',by:'赵影像',state:'历史版本'}]"><el-table-column prop="v" label="版本"/><el-table-column prop="note" label="说明"/><el-table-column prop="by" label="操作人"/><el-table-column prop="state" label="状态"/></el-table><el-button @click="version=version==='V3'?'V2':'V3'">比较 {{version}} 与 {{version==='V3'?'V2':'V3'}}</el-button><el-descriptions title="版本差异示意" :column="2" border><el-descriptions-item label="时长">V2：128分 → V3：130分</el-descriptions-item><el-descriptions-item label="文件哈希">不同 · 原件分别保留</el-descriptions-item><el-descriptions-item label="分享影响">旧链接仍为V2</el-descriptions-item><el-descriptions-item label="归档影响">需发起修订</el-descriptions-item></el-descriptions></template>
 <template v-else-if="page.id==='events'&&tab==='节目与演职'"><h3>有序节目单</h3><el-table :data="[{order:1,title:'春江月·选段',edition:'2026巡演版',planned:'35分',actual:'37分'},{order:2,title:'山河回响',edition:'2026音乐会版',planned:'25分',actual:'24分'},{order:3,title:'谢幕合唱',edition:'艺术季版',planned:'10分',actual:'11分'}]"><el-table-column prop="order" label="序号" width="65"/><el-table-column prop="title" label="节目"/><el-table-column prop="edition" label="制作版本"/><el-table-column prop="planned" label="计划时长"/><el-table-column prop="actual" label="实际时长"/></el-table><h3>计划与实际阵容对照</h3><el-table :data="[{role:'主角',planned:'演员甲',actual:'演员乙',reason:'临时替演 / 刘执行确认'},{role:'舞台监督',planned:'刘执行',actual:'刘执行',reason:'已确认'}]"><el-table-column prop="role" label="角色 / 岗位"/><el-table-column prop="planned" label="计划"/><el-table-column prop="actual" label="实际"/><el-table-column prop="reason" label="替换依据"/></el-table><el-button @click="confirm('调整节目排序')">调整节目排序</el-button><el-button @click="emit('action','确认实际阵容')">确认实际阵容</el-button><el-alert title="只有已确认的实际阵容计入参演次数；计划阵容不作为发生事实。" :closable="false"/></template>
 <template v-else-if="(page.id==='events'&&tab==='归档')||page.id==='archive'"><div class="checklist-heading"><div><h3>归档清单 · 商业剧场演出</h3><p>5 / 6项已通过 · 豁免1项单独显示</p></div><el-progress type="circle" :percentage="83" :width="90"/></div><div v-for="item in ['适用剧本','实际阵容','节目单','精选照片','全场录像','结算凭证']" :key="item" class="checklist-row"><el-checkbox v-model="checked" :value="item">{{item}}</el-checkbox><span>{{item==='结算凭证'?'财务甲 · 10月12日截止':'林档案 · 已核对'}}</span><el-tag :type="checked.includes(item)?'success':'warning'">{{checked.includes(item)?'已通过':'缺失'}}</el-tag></div><el-input v-model="reviewNote" type="textarea" placeholder="填写豁免依据或条件归档说明" aria-label="归档说明"/><el-button @click="emit('action','申请豁免')">申请豁免</el-button><el-button type="primary" @click="emit('action','提交审核')">提交条件归档</el-button><h3>归档快照</h3><p>SNAP-002 · 固定场次信息、实际人员、资料V2及权利清单。新版资料通过修订生成SNAP-003。</p></template>
 <template v-else-if="page.id==='migration'"><el-steps :active="2" simple><el-step title="只读盘点"/><el-step title="字段映射"/><el-step title="校验抽检"/><el-step title="签收"/></el-steps><h3>{{tab}}</h3><el-table :data="[{source:'HD-003 / 2024/春江月/首演.mov',field:'场次',target:'广州首演',state:'待人工确认'},{source:'HD-003 / 未命名/扫描001.pdf',field:'归属',target:'历史待整理',state:'待匹配'},{source:'HD-003 / 旧盘/损坏.mp4',field:'读取异常',target:'保留来源',state:'不能入正式库'}]"><el-table-column prop="source" label="源路径" min-width="250"/><el-table-column prop="field" label="映射字段"/><el-table-column label="候选值"><template #default="{row:r}"><el-select v-model="r.target"><el-option value="广州首演"/><el-option value="历史待整理"/><el-option value="保留来源"/></el-select></template></el-table-column><el-table-column prop="state" label="状态"/></el-table><el-alert title="文件名及目录规则只提供候选，不自动登记为正式事实。" :closable="false"/><div class="mini-metrics"><div>总文件<b>1,280</b></div><div>校验一致<b>1,277</b></div><div>异常<b>3</b></div><div>抽检目标<b>64</b></div></div><el-button @click="downloadDemo('迁移错误表-演示.csv','源路径,原因\nHD-003/旧盘/损坏.mp4,读取异常')">下载错误表</el-button><el-button @click="emit('action','重试失败项')">只重试失败项</el-button></template>
 <template v-else-if="page.id==='shares'"><template v-if="tab==='版本清单'"><el-table :data="[{name:'谢幕精选照片01—10',version:'V1',rights:'宣传使用',download:'禁止原件'},{name:'60秒宣传片',version:'V2',rights:'至2026-12-31',download:'仅预览代理'}]"><el-table-column prop="name" label="文件"/><el-table-column prop="version" label="固定版本"/><el-table-column prop="rights" label="权利依据"/><el-table-column prop="download" label="授权"/></el-table></template><template v-else-if="tab==='配额策略'"><el-descriptions :column="2" border><el-descriptions-item label="访问会话">已用2 / 上限10</el-descriptions-item><el-descriptions-item label="下载会话">未启用</el-descriptions-item><el-descriptions-item label="同时在线">1 / 上限2</el-descriptions-item><el-descriptions-item label="交付字节">未启用</el-descriptions-item><el-descriptions-item label="IP范围">203.0.113.0/24（文档示例）</el-descriptions-item></el-descriptions><p>刷新与媒体分片不计新会话；同一有效下载会话续传不重复扣次。放宽配额或IP范围需重审。</p></template><template v-else-if="tab==='外部视角'"><el-alert title="不展示内部目录、工作批注、财务字段及未选资料。" :closable="false"/><el-button type="primary" @click="emit('navigate','external-share')">打开外部接收页</el-button></template><template v-else><el-descriptions :column="1" border><el-descriptions-item label="用途">剧院巡演宣传</el-descriptions-item><el-descriptions-item label="接收人">合作剧院（指定邮箱验证）</el-descriptions-item><el-descriptions-item label="授权期限">2026-10-09 至 2026-10-16</el-descriptions-item><el-descriptions-item label="水印">接收人标识 + 分享编号 + 访问日期</el-descriptions-item></el-descriptions><el-timeline><el-timeline-item timestamp="10月09日 09:05">周宣传提交申请</el-timeline-item><el-timeline-item timestamp="10月09日 10:00">项目负责人审核用途</el-timeline-item><el-timeline-item timestamp="待确认">权利校验 / 授权生效</el-timeline-item></el-timeline><p>下载发起不代表接收人已完整保存文件。访问记录区分验证身份数与传输结果。</p></template></template>
 <template v-else-if="page.id==='approvals'"><el-alert title="本申请由周宣传发起，当前演示审核人为陈项目，申请人与审核人分离。" :closable="false"/><el-descriptions title="授权变更对照" :column="2" border><el-descriptions-item label="原授权">仅预览 / 7天 / 照片V1</el-descriptions-item><el-descriptions-item label="申请扩大">水印副本下载 / 14天</el-descriptions-item><el-descriptions-item label="权利依据">摄影宣传授权 RGT-008</el-descriptions-item><el-descriptions-item label="影响范围">10份照片 / 1位接收人</el-descriptions-item></el-descriptions><el-input v-model="reviewNote" type="textarea" placeholder="审核意见（退回时必填）"/><div class="panel-actions"><el-button @click="reviewNote.trim()?emit('action','退回'):ElMessage.warning('请填写退回原因')">退回补充</el-button><el-button type="primary" @click="emit('action','通过')">审核通过</el-button></div></template>
 <template v-else-if="['ledger','reports','settlements','allocation','channels'].includes(page.id)||(page.id==='events'&&tab==='经营')"><template v-if="page.id==='events'&&!['财务人员','项目负责人'].includes(persona)"><el-empty description="经营标签需独立财务授权，切换演示岗位后查看。"/></template><template v-else><div class="mini-metrics"><div>票款毛收入<b>¥120,000</b></div><div>已完成退款<b>¥4,000</b></div><div>票款净收入<b>¥116,000</b></div></div><el-alert :title="page.id==='allocation'?'管理口径分摊，不改写原始票房；本示例50% / 30% / 20%，合计100%。':'累计快照按确认版本替代旧值；金额按币种及统计截止日分别核对。'" :closable="false"/><el-table v-if="page.id==='allocation'" :data="[{name:'春江月选段',ratio:'50%',amount:'58,000.00'},{name:'山河回响',ratio:'30%',amount:'34,800.00'},{name:'谢幕合唱',ratio:'20%',amount:'23,200.00'}]"><el-table-column prop="name" label="节目"/><el-table-column prop="ratio" label="权重"/><el-table-column prop="amount" label="金额 / CNY"/></el-table><el-table v-else :data="[{metric:'净售票张数',source:'630',staged:'630',confirmed:'630',diff:'0'},{metric:'票款净收入',source:'116000.00',staged:'116000.00',confirmed:'116000.00',diff:'0.00'},{metric:'退款金额',source:'4000.00',staged:'4200.00',confirmed:'4000.00',diff:'+200.00 待核对'}]"><el-table-column prop="metric" label="指标"/><el-table-column prop="source" label="渠道原报表"/><el-table-column prop="staged" label="系统暂存"/><el-table-column prop="confirmed" label="财务确认"/><el-table-column prop="diff" label="差异"/></el-table><p>本场可售750座，净售票630张，售票率84%；开放800座，实际入场650人，入场率81.25%。零分母显示不适用。</p><el-input v-model="reviewNote" type="textarea" placeholder="填写复核意见或更正原因"/><el-button @click="emit('action','提交复核')">提交复核</el-button><el-button @click="downloadDemo('财务复核-演示.csv','指标,原始值,暂存值,差异\n退款金额,4000,4200,200')">下载差异表</el-button></template></template>
 <template v-else-if="page.id==='compilations'"><div class="compilation-layout"><nav><h4>年度报告大纲</h4><button v-for="c in ['年度概况','演出活动','创作成果','人才参与','社会服务','获奖报道']" :key="c" :class="{active:chapter===c}" @click="chapter=c">{{c}}</button><el-checkbox v-model="publicView">公开版字段预览</el-checkbox></nav><div><span class="kicker">源快照 SNAP-2026-01</span><h2>{{chapter}}</h2><el-input v-model="paragraph" type="textarea" :rows="8" :disabled="locked" aria-label="编纂段落"/><div class="panel-actions"><el-checkbox v-model="locked">人工锁定此段</el-checkbox><el-button @click="regenerate">重新生成本段示意</el-button><el-button type="primary" @click="saveParagraph">保存段落</el-button></div><el-alert title="2项来源已更新，1项荣誉缺凭证；正式导出前需核对。" :closable="false"/><h4>来源与待补项</h4><p>① 广州首演归档快照V2 · 已确认<br>② 巡演经营报表 · {{publicView?'公开版隐藏财务金额':'财务字段需单独授权'}}<br>③ 优秀剧目荣誉 · 凭证待核验，不进入正式稿</p><el-button @click="emit('navigate','achievements')">核对成果凭证</el-button><el-button @click="downloadDemo('成果材料-界面演示稿.txt','【仅为界面演示，非正式DOCX/PDF输出】\n'+paragraph)">预览导出内容</el-button><p class="muted">拟支持DOCX、PDF和CSV；当前只导出标记为演示的文本，未生成正式文件。</p></div></div></template>
 <template v-else-if="page.id==='permissions'&&tab==='动作矩阵'"><el-table :data="['查看元数据','预览','下载原件','上传','编辑','提交审核','审批','生成分享','导出','回收','永久销毁'].map((a,i)=>({a,allow:i<6,deny:i===10}))"><el-table-column prop="a" label="动作"/><el-table-column label="允许"><template #default="{row:r}"><el-switch v-model="r.allow" :aria-label="r.a+'允许'"/></template></el-table-column><el-table-column label="显式拒绝"><template #default="{row:r}"><el-switch v-model="r.deny" :aria-label="r.a+'拒绝'"/></template></el-table-column></el-table><el-button @click="emit('action','影响预览')">预览受影响账号与分享</el-button></template>
 <template v-else-if="(page.id==='assets'&&tab==='权利')||page.id==='rights'"><el-descriptions :column="2" border><el-descriptions-item label="权利主体">摄影工作室 / 作品权利人</el-descriptions-item><el-descriptions-item label="授权行为">内部存档；宣传预览</el-descriptions-item><el-descriptions-item label="有效期">2026-01-01 至 2026-12-31</el-descriptions-item><el-descriptions-item label="允许转授权">否</el-descriptions-item><el-descriptions-item label="外发结论">全场录像未确认，阻止外发</el-descriptions-item><el-descriptions-item label="凭证">RGT-008 / 已人工核对</el-descriptions-item></el-descriptions><el-alert title="用途、渠道、区域、接收人和期限须同时满足；续签后历史分享需重新审批。" :closable="false"/><el-button @click="emit('navigate','shares')">查看受影响分享</el-button></template>
 <template v-else-if="['关联资料','资料','适用剧本','资料引用','关联照片','剧目与资料','业务关联'].includes(tab)"><el-table :data="[{name:'春江月·定稿剧本',version:'V3',scope:'2026巡演版',state:'已确认'},{name:'谢幕精选照片',version:'V1',scope:'广州首演',state:'可外发'},{name:'全场实录',version:'V2',scope:'广州首演',state:'内部'}]"><el-table-column prop="name" label="资料"/><el-table-column prop="version" label="版本"/><el-table-column prop="scope" label="关联对象"/><el-table-column prop="state" label="状态"/></el-table><el-button @click="emit('navigate','assets')">进入资料中心</el-button><el-alert title="引用不会复制文件，也不会扩大资料自身权限。" :closable="false"/></template>
 <template v-else><h3>{{tab}}</h3><el-table :data="genericRows.map(r=>({name:r[0],value:r[1],note:r[2]}))"><el-table-column prop="name" label="项目" min-width="180"/><el-table-column prop="value" label="内容 / 当前值" min-width="200"/><el-table-column prop="note" label="状态与说明" min-width="210"/></el-table><div v-if="page.id==='productions'&&tab==='制作版本'" class="panel-actions"><el-button @click="emit('navigate','editions')">管理制作版本</el-button><el-button @click="emit('navigate','events')">新建关联场次</el-button></div><p v-if="isHistory" class="muted">审计记录只读，保存原操作者及修改前后值。当前展示示例事件。</p><el-alert v-if="page.rules.length" :title="page.rules[0]" :closable="false"/></template>
</div>
</template>
