<script setup lang="ts">
import {computed,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {type Page,statusType} from './catalog'
import {state,persist,downloadDemo} from './store'
import DetailPanels from './DetailPanels.vue'
const props=defineProps<{page:Page,persona:string}>();const emit=defineEmits(['navigate'])
const query=ref(''),filter=ref('全部状态'),layout=ref('列表'),sort=ref('默认顺序'),pageNumber=ref(1),size=ref(10),selected=ref<any[]>([]),columns=ref([...props.page.columns])
const active=ref<any>(null),tab=ref(props.page.tabs[0]||'概览'),formOpen=ref(false),form=ref<Record<string,any>>({}),editing=ref<any>(null),formStep=ref(0),advanced=ref(false),dateRange=ref<any>(null),selectedFile=ref<HTMLInputElement|null>(null)
const readOnly=computed(()=>props.persona==='普通查看')
const financialHidden=computed(()=>props.page.group==='经营管理'&&!['财务人员','项目负责人'].includes(props.persona))
const rows=computed<any[]>(()=>state.rows[props.page.id]||[])
const filtered=computed(()=>{let list=rows.value.filter(r=>(r.title+' '+r.values.join(' ')).includes(query.value)&&(filter.value==='全部状态'||r.status===filter.value));if(sort.value==='名称排序')list=[...list].sort((a,b)=>a.title.localeCompare(b.title,'zh'));if(sort.value==='最近添加')list=[...list].reverse();return list})
const visible=computed(()=>filtered.value.slice((pageNumber.value-1)*size.value,pageNumber.value*size.value))
const steps=computed(()=>['shares','migration','ledger','recognition','compilations','backups'].includes(props.page.id)?['填写信息','范围与影响','确认提交']:['填写信息'])
const actions=computed(()=>({uploads:['暂停','继续','取消'],tasks:['重试','取消','领取结果'],migration:['匹配归属','重试失败项','业务签收'],archive:['提交审核','申请豁免','创建修订'],shares:['预览外部视角','申请扩权','撤销分享'],approvals:['通过','退回','转交'],recycle:['恢复','申请销毁'],recognition:['打开校订','重试失败页','取消'],people:['合并人员'],editions:['复制版本'],events:['确认实际阵容','改期','取消场次'],'collection-tasks':['接收投稿','退回补充','外部投稿视角'],storage:['申请取回','生成迁移候选'],backups:['恢复演练','导出清单'],models:['质量评估','版本回退'],channels:['同步预览','提交对账复核'],ledger:['导入预览','提交复核','申请更正'],compilations:['打开编纂稿','提交审核','导出预览'],permissions:['影响预览']})[props.page.id]||['编辑记录','查看变更'])
function open(row:any){active.value=row;tab.value=props.page.tabs[0]||'概览'}
function edit(row?:any){editing.value=row||null;formStep.value=0;form.value=row?{...row.form}:JSON.parse(JSON.stringify(state.drafts[props.page.id]||{}));if(row&&props.page.fields[0])form.value[props.page.fields[0].key]=row.title;formOpen.value=true}
function primary(){if(props.page.id==='assets'){emit('navigate','uploads');return}if(props.page.id==='uploads'){selectedFile.value?.click();return}if(props.page.id==='inbox'){rows.value.forEach(r=>r.status='已读');persist();ElMessage.success('演示消息已标记为已读');return}edit()}
async function closeForm(done?:()=>void){if(Object.values(form.value).some(v=>v!==''&&v!=null)){try{await ElMessageBox.confirm('尚未提交的内容可以保存为本地演示草稿。','离开表单',{confirmButtonText:'保存草稿并离开',cancelButtonText:'继续填写'});state.drafts[props.page.id]=safeForm();persist()}catch{return}}formOpen.value=false;done?.()}
function safeForm(){return Object.fromEntries(Object.entries(form.value).filter(([key])=>!props.page.fields.some(f=>f.key===key&&f.type==='password')))}
function draft(){state.drafts[props.page.id]=safeForm();persist();ElMessage.success('演示草稿已保存在本浏览器')}
function submit(){const missing=props.page.fields.find(f=>f.required&&!String(form.value[f.key]??'').trim());if(missing){ElMessage.warning('请填写'+missing.label);return}if(props.page.id==='allocation'){const sum=['节目一比例（%）','节目二比例（%）','节目三比例（%）'].reduce((s,k)=>s+Number(form.value[k]||0),0);if(form.value['方法']==='人工比例'&&sum!==100){ElMessage.warning('分摊比例合计须为100%');return}}if(formStep.value<steps.value.length-1){formStep.value++;return}
const title=form.value['名称']||form.value['标题']||form.value['姓名']||form.value['账号']||form.value['场次']||`${props.page.title}演示记录`
if(editing.value){Object.assign(editing.value,{title,form:safeForm()})}else{rows.value.unshift({id:`${props.page.id}-${Date.now()}`,title,status:'草稿',values:props.page.columns.slice(2).map((c,i)=>form.value[c]||Object.values(safeForm())[i+1]||'待补充'),form:safeForm()})}
delete state.drafts[props.page.id];persist();formOpen.value=false;ElMessage.success('已保存演示记录，未提交业务服务')}
async function action(label:string,row=active.value){if(!row)return;if(label.includes('外部视角')){emit('navigate',label.includes('投稿')?'external-submit':'external-share');return}if(label==='打开校订'){emit('navigate',row.title.includes('转写')?'transcripts':'proofread');return}if(label==='打开编纂稿'){open(row);tab.value='编纂任务';return}if(label==='影响预览'){open(row);tab.value='影响预览';return}if(label==='质量评估'){open(row);tab.value='质量评估';return}if(['编辑记录','申请扩权','申请更正','改期','复制版本','合并人员','转交','匹配归属','申请取回'].includes(label)){edit(row);return}if(label.includes('导出')||label==='领取结果'){downloadDemo(`${props.page.title}-演示清单.json`,{说明:'界面评审示例，不是真实业务导出',记录:row});return}
try{await ElMessageBox.confirm(`${label}「${row.title}」？本操作仅改变演示状态。涉及实际文件、分享和资金的处理将在界面确认后实现。`,label,{confirmButtonText:'确认演示操作',cancelButtonText:'取消'});row.status=label==='暂停'?'已暂停':label==='继续'?'上传中':label.includes('重试')?'处理中':label==='通过'?'审批通过':label.includes('退回')?'退回补充':label.includes('撤销')?'已撤销':label==='恢复'?'已恢复':label.includes('取消')?'已取消':label.includes('签收')?'已签收':label.includes('接收')?'已接收':label.includes('销毁')?'待第二人确认':label.includes('实际')?'实际阵容已确认':label.includes('审核')||label.includes('复核')?'待审批':'待处理';persist();ElMessage.success('演示状态已更新')}catch{}}
async function batch(){if(!selected.value.length){ElMessage.warning('请先选择记录');return}try{const {value}=await ElMessageBox.prompt(`将影响${selected.value.length}条演示记录。请填写批量整理说明。`,'批量整理',{inputPlaceholder:'例如：标记为年度申报候选',inputValidator:v=>!!v?.trim()||'请填写说明'});selected.value.forEach(r=>r.batchNote=value);persist();ElMessage.success(`已更新${selected.value.length}条演示记录`)}catch{}}
function addFiles(event:Event){const files=Array.from((event.target as HTMLInputElement).files||[]);files.forEach(file=>rows.value.unshift({id:'demo-'+Date.now()+'-'+file.name,title:file.name,status:'待传输',values:[`${(file.size/1048576).toFixed(1)} MB`,'仅登记文件名 · 未上传','0%']}));persist();ElMessage.info(`已登记${files.length}个文件名用于界面演示，文件内容未上传`)}
</script>
<template>
<div v-if="financialHidden" class="surface state-panel"><span class="state-symbol">—</span><h2>经营数据需要独立授权</h2><p>切换右上角演示岗位为“财务人员”，查看台账、复核和报表界面。</p></div>
<div v-else>
 <div v-if="page.id==='reports'" class="report-cards"><div class="metric"><span>已完成场次</span><b>20<small>场</small></b><p>按场次ID去重 · 演示</p></div><div class="metric"><span>净售票张数</span><b>12,600</b><p>已扣全额退票 · 不含赠票</p></div><div class="metric"><span>票款净收入 / CNY</span><b>232<small>万元</small></b><p>演出日期口径 · 已确认数据</p></div><div class="metric"><span>数据截止</span><b class="small-value">2026.10.09</b><p>累计快照不重复叠加</p></div></div>
 <div v-if="['search','semantic'].includes(page.id)" class="search-hero"><div><span class="kicker">{{page.id==='semantic'?'按含义找到线索':'每份资料，都有来处'}}</span><h2>{{page.id==='semantic'?'近三年适合校园演出的亲情题材剧目':'从一段记忆，找到完整档案。'}}</h2><p>{{page.id==='semantic'?'示例解析范围：2024-01-01 至 2026-12-31 · 标签为候选判断，需查看依据':'试试：春江月 / 广州 / 全场实录，或演员的实际参演记录。'}}</p></div><span class="hero-seal">检索</span></div>
 <div v-if="page.id==='uploads'" class="upload-drop" @dragover.prevent @drop.prevent="ElMessage.info('演示版请使用选择文件按钮，仅登记文件名')"><span>＋</span><h3>文件与目录，集中入库</h3><p>选择归属 → 分片传输 → 完整校验 → 安全检查 → 生成预览</p><el-button type="primary" @click="selectedFile?.click()">选择文件</el-button><el-button @click="edit()">登记归属与同名规则</el-button><small>200GB上限为需求展示 · 本页不传输真实文件</small></div>
 <input ref="selectedFile" type="file" multiple hidden @change="addFiles"/>
 <div v-if="page.id==='storage'" class="storage-strip surface"><div><b>主存储空间</b><p>原件、历史版本、衍生件与临时数据分别统计</p></div><el-progress :percentage="72" :stroke-width="12" color="#b18d54"/><span>演示：43.2 / 60 TB</span></div>
 <div class="surface data-surface">
  <div class="surface-title"><div><h3>{{page.title}}</h3><span>{{filtered.length}}条演示记录</span></div><div><el-button v-if="!readOnly" type="primary" @click="primary">{{page.action}}</el-button><el-button @click="downloadDemo(page.title+'-演示记录.json',{说明:'仅为界面评审样例',记录:filtered})">导出演示清单</el-button></div></div>
  <div class="table-toolbar"><el-input v-model="query" placeholder="输入名称、编号或关键词" clearable aria-label="筛选记录" @input="pageNumber=1"/><el-select v-model="filter" aria-label="筛选状态" @change="pageNumber=1"><el-option value="全部状态"/><el-option v-for="s in [...new Set(rows.map(r=>r.status))]" :key="String(s)" :value="s"/></el-select><el-button @click="advanced=!advanced">{{advanced?'收起筛选':'更多筛选'}}</el-button><div class="toolbar-spacer"></div><el-select v-model="sort" aria-label="排序"><el-option v-for="s in ['默认顺序','名称排序','最近添加']" :key="s" :value="s"/></el-select><el-radio-group v-if="['assets','search','semantic','collections','productions'].includes(page.id)" v-model="layout"><el-radio-button value="列表">列表</el-radio-button><el-radio-button value="网格">网格</el-radio-button></el-radio-group><el-popover trigger="click" width="220"><template #reference><el-button>显示列</el-button></template><el-checkbox-group v-model="columns"><el-checkbox v-for="c in page.columns" :key="c" :value="c">{{c}}</el-checkbox></el-checkbox-group></el-popover></div>
  <div v-if="advanced" class="advanced-filter"><el-date-picker v-model="dateRange" type="daterange" start-placeholder="开始日期" end-placeholder="结束日期"/><el-input placeholder="责任人 / 标签" @input="(v:string)=>query=v"/><el-button @click="query='';filter='全部状态';dateRange=null">清空条件</el-button><p>演示按关键词与状态筛选，日期范围供界面评审。</p></div>
  <div v-if="selected.length" class="selection-bar">已选择 {{selected.length}} 项 <el-button text @click="batch">批量整理</el-button><el-button text @click="downloadDemo('批量导出-演示.json',selected)">导出所选</el-button></div>
  <div v-if="layout==='网格'" class="asset-grid"><button v-for="r in visible" :key="r.id" class="asset-card" @click="open(r)"><div class="art-preview" :class="r.type||'document'"><span>{{r.type==='video'?'▶':r.type==='image'?'光影 · 舞台':'文艺档案'}}</span><small>{{r.type==='video'?'02:08:36':'演示素材'}}</small></div><div class="asset-card-body"><el-tag size="small" :type="statusType(r.status)">{{r.status}}</el-tag><h3>{{r.title}}</h3><p>{{r.values.join(' · ')}}</p></div></button></div>
  <el-table v-else :data="visible" @selection-change="selected=$event" empty-text="没有符合条件的记录，试试清空筛选。" row-key="id"><el-table-column type="selection" width="44"/><el-table-column v-for="(c,i) in page.columns.filter(c=>columns.includes(c))" :key="c" :label="c" :min-width="i===0?240:130"><template #default="{row}"><button v-if="c===page.columns[0]" class="record-link" @click="open(row)"><span class="file-icon">{{page.phase.includes('P2')?'智':page.group==='经营管理'?'账':page.group==='系统管理'?'设':'档'}}</span><span>{{row.title}}<small>{{row.id.toUpperCase()}}</small></span></button><el-tag v-else-if="c==='状态'" :type="statusType(row.status)" effect="light">{{row.status}}</el-tag><span v-else>{{row.values[page.columns.indexOf(c)-2]??'—'}}</span></template></el-table-column><el-table-column label="操作" fixed="right" width="130"><template #default="{row}"><el-button text type="primary" @click="open(row)">详情</el-button><el-dropdown v-if="!readOnly" @command="(v:string)=>action(v,row)"><el-button text aria-label="更多操作">···</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item v-for="a in actions" :key="a" :command="a">{{a}}</el-dropdown-item></el-dropdown-menu></template></el-dropdown></template></el-table-column></el-table>
  <el-empty v-if="layout==='网格'&&!visible.length" description="没有符合条件的记录"/>
  <div class="table-bottom"><span>演示记录 · {{page.phase}}</span><el-pagination v-model:current-page="pageNumber" v-model:page-size="size" :page-sizes="[10,20,50]" :total="filtered.length" layout="sizes, prev, pager, next"/></div>
 </div>
 <div v-if="page.rules.length" class="rule-strip"><b>业务规则</b><span v-for="r in page.rules" :key="r">{{r}}</span></div>
 <el-drawer :model-value="!!active" @close="active=null" size="min(1080px,98vw)" :title="page.title+' · 详情'" class="proto-drawer">
  <template v-if="active"><div class="detail-heading"><div><el-tag :type="statusType(active.status)">{{active.status}}</el-tag><h2>{{active.title}}</h2><p>{{active.id.toUpperCase()}} · 演示记录 · 最近更新 2026-10-09</p></div><el-button v-if="!readOnly&&page.id!=='audit'" @click="edit(active)">编辑信息</el-button></div><el-tabs v-model="tab"><el-tab-pane v-for="t in page.tabs" :key="t" :label="t" :name="t"/></el-tabs><DetailPanels :page="page" :row="active" :tab="tab" :persona="persona" @navigate="emit('navigate',$event)" @action="action($event)"/><div class="detail-footer"><el-button v-for="a in actions.slice(0,3)" :key="a" :disabled="readOnly" @click="action(a)">{{a}}</el-button></div></template>
 </el-drawer>
 <el-dialog v-model="formOpen" :title="(editing?'编辑 · ':'新建 · ')+page.title" width="min(780px,96vw)" :before-close="closeForm" class="proto-form-dialog">
  <el-steps v-if="steps.length>1" :active="formStep" finish-status="success" simple><el-step v-for="s in steps" :key="s" :title="s"/></el-steps>
  <el-form v-if="formStep===0" label-position="top" @submit.prevent="submit" class="prototype-form"><el-form-item v-for="field in page.fields" :key="field.key" :label="field.label" :required="field.required" :class="{wide:field.type==='textarea'}"><el-select v-if="field.type==='select'" v-model="form[field.key]" :aria-label="field.label" clearable><el-option v-for="o in field.options" :key="o" :value="o"/></el-select><el-switch v-else-if="field.type==='switch'" v-model="form[field.key]" :aria-label="field.label"/><el-date-picker v-else-if="['date','datetime'].includes(field.type||'')" v-model="form[field.key]" :type="field.type==='date'?'date':'datetime'" :aria-label="field.label" value-format="YYYY-MM-DDTHH:mm:ss"/><el-input-number v-else-if="field.type==='number'" v-model="form[field.key]" :min="0" :aria-label="field.label"/><el-input v-else v-model="form[field.key]" :type="field.type==='textarea'?'textarea':field.type==='password'?'password':'text'" :rows="3" :aria-label="field.label" :placeholder="'填写'+field.label" :autocomplete="field.type==='password'?'new-password':'off'"/></el-form-item></el-form>
  <div v-else class="wizard-review"><h3>{{formStep===1?'范围与影响确认':'提交前复核'}}</h3><el-descriptions :column="1" border><el-descriptions-item v-for="(v,k) in form" :key="k" :label="String(k)">{{String(k).includes('凭证')||String(k).includes('密钥')?'已填写（不展示）':v||'未填写'}}</el-descriptions-item></el-descriptions><ul><li v-for="r in page.rules" :key="r">{{r}}</li></ul><el-alert title="仅保存演示状态；不发送通知、不执行导入、不生成真实外链。" :closable="false"/></div>
  <template #footer><el-button @click="draft">保存草稿</el-button><el-button v-if="formStep>0" @click="formStep--">上一步</el-button><el-button @click="closeForm()">取消</el-button><el-button type="primary" @click="submit">{{formStep<steps.length-1?'下一步':'保存演示记录'}}</el-button></template>
 </el-dialog>
</div>
</template>
