<script setup lang="ts">
import {ref,computed} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {pages,type Page,statusType} from './catalog'
import {state,persist,downloadDemo} from './store'
const props=defineProps<{page:Page,persona:string}>();const emit=defineEmits(['navigate','export'])
const reviewFilter=ref('全部'),reviewQuery=ref(''),notePage=ref('dashboard'),reviewOpen=ref(false)
const reviewPages=computed(()=>pages.filter(p=>(reviewFilter.value==='全部'||p.phase.includes(reviewFilter.value))&&(p.title+p.req).includes(reviewQuery.value)))
const stateChoice=ref('未验证'),verification=ref(''),address=ref(''),authMode=ref('邮箱验证码'),verified=ref(false),sent=ref(false),consent=ref(false),files=ref<string[]>(['谢幕照片01.jpg','摄影授权声明.pdf'])
const externalUnavailable=computed(()=>['已到期','已撤销','次数用尽','IP不匹配'].includes(stateChoice.value))
const ocrPage=ref(12),selectedBlock=ref(0),lowOnly=ref(false),ocrMode=ref('人工校订稿'),blocks=ref([{text:'第二幕 · 月上柳梢',confidence:99},{text:'这条河，记得每一个归来的人。',confidence:96},{text:'灯光渐亮，远处传来渡船的声音。',confidence:72}]),ocrSaved=ref(false)
const position=ref(754),speed=ref('1.0×'),playing=ref(false),activeTab=ref('转写校订'),annotation=ref(''),clipStart=ref(754),clipEnd=ref(814),clipPurpose=ref(''),speaker=ref('说话人1'),region=ref<{x:number,y:number}|null>(null)
const segments=ref([{start:742,end:754,text:'这一段的情绪可以再慢一点。',speaker:'说话人1',confirmed:false},{start:754,end:769,text:'等灯光落下，再接下一句。',speaker:'说话人2',confirmed:true},{start:770,end:791,text:'观众需要一点时间理解人物的选择。',speaker:'说话人1',confirmed:false}])
const question=ref(''),answer=ref(''),answerState=ref(''),scope=ref('春江月 / 2026年 / 已确认资料'),messages=ref<string[]>([]),answerLoading=ref(false),sourceOpen=ref(false),feedback=ref('')
const selectedPhotos=ref<number[]>([1]),split=ref(false),photoReason=ref('表情自然，舞台主体完整'),compareZoom=ref(100)
const calendar=['日','一','二','三','四','五','六']
function remember(){persist();ElMessage.success('评审意见已保存到本浏览器')}
function review(id:string){notePage.value=id;reviewOpen.value=true}
function verify(){if(!address.value.trim()){ElMessage.warning('请填写接收身份');return}if(verification.value!=='246810'){ElMessage.error('验证未通过，请检查输入后重试。演示验证码为246810。');return}verified.value=true;stateChoice.value='已验证';ElMessage.success('已进入模拟验证后的页面')}
function saveOCR(){state.drafts['ocr-review']={page:ocrPage.value,blocks:blocks.value};persist();ocrSaved.value=true;ElMessage.success('校订演示稿已保存，原图保持不变')}
function splitBlock(){const b=blocks.value[selectedBlock.value];if(!b)return;const middle=Math.ceil(b.text.length/2);blocks.value.splice(selectedBlock.value,1,{...b,text:b.text.slice(0,middle)},{...b,text:b.text.slice(middle)});ocrSaved.value=false}
function mergeBlock(){const i=selectedBlock.value;if(!blocks.value[i+1]){ElMessage.info('请选择有下一块的文字');return}blocks.value[i].text+=blocks.value[i+1].text;blocks.value.splice(i+1,1);ocrSaved.value=false}
function saveTranscript(){if(segments.value.some(s=>s.start<0||s.end<=s.start||s.end>2520)){ElMessage.warning('时间码须满足0≤开始<结束≤源时长2520秒');return}state.drafts['transcript-review']=segments.value;persist();ElMessage.success('已保存人工稿示意，机器初稿仍保留')}
function clip(){if(clipStart.value<0||clipEnd.value<=clipStart.value||clipEnd.value>2520){ElMessage.warning('请检查片段起止时间');return}if(!clipPurpose.value.trim()){ElMessage.warning('请填写片段用途');return}ElMessage.success('已记录演示选段申请，未转码或生成真实片段')}
function mark(e:MouseEvent){const rect=(e.currentTarget as HTMLElement).getBoundingClientRect();region.value={x:Math.round((e.clientX-rect.left)/rect.width*100),y:Math.round((e.clientY-rect.top)/rect.height*100)}}
async function ask(text=question.value){if(!text.trim())return;question.value=text;answerLoading.value=true;messages.value.push(text);await new Promise(r=>setTimeout(r,300));answerState.value=/无|未知|获奖/.test(text)?'证据不足':/冲突|不同/.test(text)?'来源冲突':'有依据';answer.value=answerState.value==='证据不足'?'当前可访问资料不足以确认。示例档案尚无已核验的对应成果记录，可请负责人补充凭证后再查询。':answerState.value==='来源冲突'?'两份演示记录的实际时长不同：场次记录为128分钟，录像文件为130分钟。可能包含谢幕片段，应由业务负责人核对，本页不自动覆盖档案。':'根据演示归档记录，《春江月》广州首演于2026年10月8日在城市剧院举行，实际主角为演员乙。[1] 对应归档录像为V2；当前工作版本已更新为V3，旧分享仍固定V2。[2]';answerLoading.value=false}
function exampleFile(e:Event){files.value.push(...Array.from((e.target as HTMLInputElement).files||[]).map(f=>f.name));ElMessage.info('仅登记本地文件名，未上传文件内容')}
async function submitContribution(){if(!consent.value){ElMessage.warning('请阅读并勾选授权声明');return}await ElMessageBox.alert('演示投稿已进入“待审核”。实际功能实现后还需经过隔离检查、权利核验和内部接收。','投稿流程演示');stateChoice.value='待审核'}
</script>
<template>
<div v-if="page.special==='dashboard'">
 <div class="welcome-panel"><div><span class="kicker">2026年10月9日 · 星期五</span><h2>让舞台上的每一刻，<br>成为可寻找的记忆。</h2><p>今天有3项归档待办、2份分享申请，以及1项即将到期的授权。</p><el-button type="primary" @click="emit('navigate','inbox')">处理我的待办 →</el-button><el-button @click="emit('navigate','uploads')">上传演出资料</el-button></div><div class="curtain-art"><div class="curtain left"></div><div class="curtain right"></div><span>春<br>江<br>月</span><small>2026 · 秋季巡演</small></div></div>
 <div class="overview-metrics"><button @click="emit('navigate','productions')"><span>在演剧目</span><strong>12<small>部</small></strong><p>关联38个制作版本</p></button><button @click="emit('navigate','events')"><span>本年度演出</span><strong>86<small>场</small></strong><p>已完成 · 按场次去重</p></button><button @click="emit('navigate','archive')"><span>归档完整率</span><strong>92<small>%</small></strong><p>6场资料待补齐</p></button><button @click="emit('navigate','shares')"><span>生效分享</span><strong>18<small>份</small></strong><p>3份将在7日内到期</p></button></div>
 <div class="dashboard-columns"><section class="surface"><div class="surface-title"><h3>需要你关注</h3><button @click="emit('navigate','inbox')">全部待办 →</button></div><button v-for="(item,i) in [{name:'广州首演缺少结算凭证',meta:'归档检查 · 林档案 · 今日截止',to:'archive'},{name:'巡演高清照片申请外发',meta:'分享审批 · 周宣传 · 10份资料',to:'approvals'},{name:'全场录像授权即将到期',meta:'权利提醒 · 还剩9天',to:'rights'}]" :key="item.name" class="todo-row" @click="emit('navigate',item.to)"><span class="todo-number">0{{i+1}}</span><div><b>{{item.name}}</b><small>{{item.meta}}</small></div><span>↗</span></button></section><section class="surface calendar-panel"><div class="surface-title"><h3>十月演出日历</h3><button @click="emit('navigate','events')">查看场次 →</button></div><div class="calendar-grid"><span v-for="d in calendar" :key="d">{{d}}</span><button v-for="n in 31" :key="n" :class="{today:n===9,event:[8,18,21,25].includes(n)}" @click="emit('navigate','events')">{{n}}</button></div><p>18日 · 秋日艺术季开幕晚会</p></section></div>
 <div class="surface recent-panel"><div class="surface-title"><h3>继续整理</h3><button @click="emit('navigate','assets')">资料中心 →</button></div><div class="recent-grid"><button v-for="(item,i) in ['春江月 · 全场实录','巡演定稿剧本 V3','谢幕精选照片','年度申报资料集']" :key="item" @click="emit('navigate',i===3?'collections':'assets')"><div class="mini-art" :class="'variation-'+i"><span>{{i===1?'剧本':i===3?'精选':'舞台'}}</span></div><b>{{item}}</b><small>{{i===0?'归档V2 · 当前V3':'今天更新 · 演示资料'}}</small></button></div></div>
</div>
<div v-else-if="page.special==='review'" class="surface review-list"><div class="surface-title"><div><h3>{{pages.length}}个页面 · 全阶段评审</h3><span>确认的是界面，不是后台功能或上线验收</span></div><el-button type="primary" @click="emit('export')">导出评审记录</el-button></div><div class="table-toolbar"><el-input v-model="reviewQuery" placeholder="查找页面或需求编号"/><el-select v-model="reviewFilter"><el-option v-for="p in ['全部','P0','P1','P2']" :key="p" :value="p"/></el-select></div><el-table :data="reviewPages"><el-table-column label="页面" min-width="180"><template #default="{row}"><button class="text-link" @click="emit('navigate',row.id)">{{row.title}} ↗</button></template></el-table-column><el-table-column prop="phase" label="阶段" width="95"/><el-table-column prop="req" label="需求编号" min-width="190"/><el-table-column label="确认状态" width="150"><template #default="{row}"><el-select v-model="state.reviews[row.id]" placeholder="待评审" @change="persist"><el-option v-for="s in ['待评审','需要调整','界面已确认']" :key="s" :value="s"/></el-select></template></el-table-column><el-table-column label="意见" min-width="220"><template #default="{row}"><el-input v-model="state.notes[row.id]" placeholder="记录字段、布局或流程意见" @change="persist"/></template></el-table-column></el-table><p class="muted">记录仅保存在当前浏览器。更换设备前请导出，页面确认不触发后台开发或发布。</p></div>
<div v-else-if="page.special==='external-share'||page.special==='external-submit'" class="external-preview">
 <div class="external-demo-state"><b>外部页面状态预览</b><el-select v-model="stateChoice" aria-label="外部状态"><el-option v-for="s in page.special==='external-share'?['未验证','已验证','部分失效','处理中','已到期','已撤销','次数用尽','IP不匹配']:['未验证','已验证','待审核','退回补充','截止','超额']" :key="s" :value="s"/></el-select><el-button text @click="emit('navigate',page.special==='external-share'?'shares':'collection-tasks')">返回内部管理</el-button></div>
 <div class="external-card surface"><div class="external-brand">剧藏 <small>受控资料{{page.special==='external-share'?'分享':'征集'}}</small></div>
  <template v-if="externalUnavailable||['截止','超额'].includes(stateChoice)"><el-empty :description="['截止','超额'].includes(stateChoice)?'投稿已截止或超过配额，请联系邀请方。':'当前链接不可访问，请联系发送人。'"/><p>不显示内部文件名、目录或联系人信息。</p></template>
  <template v-else-if="stateChoice==='未验证'"><span class="external-lock">○</span><h2>请先验证接收身份</h2><p>验证后才能查看获批文件或本人投稿记录。</p><el-form label-position="top" @submit.prevent="verify"><el-form-item label="验证方式"><el-select v-model="authMode"><el-option v-for="m in ['邮箱验证码','手机号验证码','合作账号','独立提取码']" :key="m" :value="m"/></el-select></el-form-item><el-form-item label="指定接收身份"><el-input v-model="address" placeholder="演示：partner@example.com" aria-label="指定接收身份"/></el-form-item><el-form-item label="验证码 / 提取码"><el-input v-model="verification" aria-label="验证码" placeholder="演示码246810"><template #append><el-button @click="sent=true;ElMessage.info('验证码发送为演示，未发送邮件或短信')">{{sent?'已模拟发送':'获取演示码'}}</el-button></template></el-input></el-form-item><el-button native-type="submit" type="primary" style="width:100%">验证并继续</el-button></el-form><p class="muted">演示码：246810。此页不会验证真实身份。</p></template>
  <template v-else-if="page.special==='external-share'"><el-tag type="success">已验证 · 合作剧院（演示）</el-tag><h2>春江月 · 巡演宣传资料</h2><p>用途：剧院宣传预览 · 有效至2026年10月16日</p><el-alert v-if="stateChoice==='部分失效'" title="部分资料已不可用" :closable="false"/><el-alert v-if="stateChoice==='处理中'" title="水印副本正在生成，请稍后查看。不会回退提供原件。" :closable="false"/><div class="external-files"><button v-for="name in stateChoice==='部分失效'?['精选宣传照片']:['精选宣传照片','60秒宣传片']" :key="name" @click="stateChoice==='处理中'?ElMessage.info('演示：预览处理中'):sourceOpen=true"><span class="external-file-art">{{name.includes('照片')?'光影':'▶'}}</span><div><b>{{name}}</b><small>固定版本V1 · 仅预览</small></div><span>打开 →</span></button></div><p class="muted">水印：接收人 + 分享编号 + 日期。请按授权用途使用；预览不能防止截图或录屏。</p><el-button @click="stateChoice='未验证';verified=false">结束本次访问</el-button></template>
  <template v-else><el-tag type="success">本人投稿空间 · 演示</el-tag><h2>广州首演影像征集</h2><p>截止：2026-10-12 18:00 · 剩余容量62GB / 100GB</p><el-alert v-if="stateChoice==='退回补充'" title="请补交摄影授权凭证，并填写作者及拍摄日期。" :closable="false"/><el-form label-position="top"><el-form-item label="作者 / 单位"><el-input model-value="摄影工作室"/></el-form-item><el-form-item label="拍摄日期"><el-date-picker model-value="2026-10-08" type="date"/></el-form-item><el-form-item label="内容说明"><el-input type="textarea" placeholder="说明场次、机位或拍摄内容"/></el-form-item></el-form><label class="file-pick">选择投稿文件<input type="file" multiple @change="exampleFile"/></label><ul class="submission-files"><li v-for="(name,i) in files" :key="i"><span>{{name}}</span><el-tag>{{stateChoice==='待审核'?'待审核':'待提交'}}</el-tag><el-button text @click="files.splice(i,1)">移除</el-button></li></ul><el-checkbox v-model="consent">我已阅读授权声明，并愿意提交凭证供院团核验。</el-checkbox><p class="muted">声明不自动代表权利完整；接收前可撤回，接收后需申请更正。此界面不上传文件内容。</p><el-button type="primary" @click="submitContribution">提交演示投稿</el-button></template>
 </div>
 <el-dialog v-model="sourceOpen" title="受控预览示意" width="min(740px,95vw)"><div class="media-stage"><h2>春江月</h2><p>合作剧院 · SH-008 · 2026-10-09</p><span>预览示意，非真实媒体</span></div></el-dialog>
</div>
<div v-else-if="page.special==='proofread'" class="surface editor-workspace"><div class="editor-toolbar"><div><b>历史节目单.pdf · 源文件V1</b><p>识别结果R2 · 原图不变</p></div><el-select v-model="ocrMode" style="width:150px"><el-option value="机器初稿"/><el-option value="人工校订稿"/></el-select><el-switch v-model="lowOnly" active-text="仅低置信度"/><el-button @click="saveOCR">保存草稿</el-button><el-button type="primary" @click="saveOCR();ElMessage.success('人工确认状态已演示')">确认校订稿</el-button></div><div class="proof-columns"><div class="source-paper"><div class="page-switch"><el-button @click="ocrPage=Math.max(1,ocrPage-1)">上一页</el-button><span>第{{ocrPage}} / 24页</span><el-button @click="ocrPage=Math.min(24,ocrPage+1)">下一页</el-button></div><div class="document-page"><small>原图版面示意</small><h2>春江月 · 演出节目单</h2><button v-for="(b,i) in blocks" :key="i" :class="{chosen:selectedBlock===i}" @click="selectedBlock=i">{{b.text}}</button><div class="document-lines"></div><p>点选文字区域，对照右侧识别内容。</p></div></div><div class="text-editor"><h3>文字块 · 阅读顺序</h3><div v-for="(b,i) in blocks" v-show="!lowOnly||b.confidence<85" :key="i" class="ocr-block" :class="{chosen:selectedBlock===i}" @click="selectedBlock=i"><div><b>块{{i+1}}</b><el-tag :type="b.confidence<85?'warning':'success'">{{b.confidence<85?'需校订':'较高置信度'}} · {{b.confidence}}%</el-tag></div><el-input v-model="b.text" type="textarea" :rows="3" :disabled="ocrMode==='机器初稿'" :aria-label="'文字块'+(i+1)" @input="ocrSaved=false"/></div><div class="panel-actions"><el-button @click="splitBlock">拆分选中块</el-button><el-button @click="mergeBlock">合并下一块</el-button><el-button @click="selectedBlock>0&&([blocks[selectedBlock-1],blocks[selectedBlock]]=[blocks[selectedBlock],blocks[selectedBlock-1]])">上移阅读顺序</el-button></div><p>{{ocrSaved?'人工稿已保存 · 演示':'尚有未保存校订'}}</p><el-button @click="downloadDemo('OCR校订-演示.txt','【演示校订稿】\n'+blocks.map(b=>b.text).join('\n'))">导出TXT演示稿</el-button><el-alert title="可搜索PDF将另建衍生件；对外提供识别文本需独立授权。" :closable="false"/></div></div></div>
<div v-else-if="page.special==='transcripts'" class="surface editor-workspace"><div class="editor-toolbar"><div><b>导演排练讨论.mp4 · V2 · 音轨1</b><p>源时长42分钟 · 机器稿与人工稿分开保留</p></div><el-button type="primary" @click="saveTranscript">保存人工稿</el-button><el-button @click="downloadDemo('转写-演示.txt',segments)">导出演示文本</el-button></div><el-tabs v-model="activeTab"><el-tab-pane v-for="t in page.tabs" :key="t" :name="t" :label="t"/></el-tabs><div class="media-editor"><div><div class="media-stage annotation-canvas" @click="activeTab==='图片区域'&&mark($event)"><h2>春江月</h2><p>{{activeTab==='图片区域'?'点击画面标记归一化位置':'媒体预览示意 · 未载入真实媒体'}}</p><button v-if="activeTab!=='图片区域'" class="play-control" @click.stop="playing=!playing">{{playing?'Ⅱ':'▶'}}</button><span v-if="region" class="region-mark" :style="{left:region.x+'%',top:region.y+'%'}"></span></div><el-slider v-model="position" :max="2520"/><div class="media-controls"><span>{{Math.floor(position/60)}}:{{String(position%60).padStart(2,'0')}} / 42:00</span><el-select v-model="speed" style="width:90px"><el-option v-for="r in ['0.5×','1.0×','1.5×','2.0×']" :key="r" :value="r"/></el-select><el-button @click="clipStart=position;activeTab='选段申请'">标记选段起点</el-button></div><el-alert title="说话人标签不代表身份识别；有证据后才能人工关联人员。" :closable="false"/></div><div>
<template v-if="activeTab==='转写校订'"><div v-for="(s,i) in segments" :key="i" class="transcript-line"><button @click="position=Math.max(0,s.start-3)">{{Math.floor(s.start/60)}}:{{s.start%60}} → 播放定位</button><el-select v-model="s.speaker" style="width:130px"><el-option value="说话人1"/><el-option value="说话人2"/><el-option value="人工绑定：许导演"/></el-select><el-input v-model="s.text" type="textarea" :rows="2"/><el-checkbox v-model="s.confirmed">人工确认</el-checkbox><div><el-input-number v-model="s.start" :min="0" :max="2520" size="small"/><span> 至 </span><el-input-number v-model="s.end" :min="0" :max="2520" size="small"/></div></div></template>
<template v-else-if="activeTab==='选段申请'"><h3>单源连续选段</h3><el-form label-position="top"><el-form-item label="起点（秒）"><el-input-number v-model="clipStart"/></el-form-item><el-form-item label="终点（秒）"><el-input-number v-model="clipEnd"/></el-form-item><el-form-item label="用途"><el-input v-model="clipPurpose" type="textarea"/></el-form-item><el-form-item label="输出"><el-select model-value="720p水印代理"><el-option value="720p水印代理"/><el-option value="1080p水印代理"/></el-select></el-form-item></el-form><p>父版本：V2 · 片段{{clipEnd-clipStart}}秒 · 权利未确认不得外发</p><el-button type="primary" @click="clip">提交选段申请</el-button></template>
<template v-else-if="activeTab==='来源关系'"><div class="dependency-card">原片V2 → 片段V1 → 宣传分享SH-008</div><p>源片授权失效后，派生片段与相关分享暂停新访问。单独授权需保留依据并人工审核。</p><el-button @click="emit('navigate','rights')">核对源权利</el-button></template>
<template v-else><h3>{{activeTab==='图片区域'?'区域标注':'时间点备注'}}</h3><p>位置：{{region?'X '+region.x+'% / Y '+region.y+'%':position+'秒'}} · 源版本V2</p><el-input v-model="annotation" type="textarea" :rows="4" placeholder="记录舞台问题、精彩片段或一般说明"/><el-select model-value="项目内可见"><el-option value="项目内可见"/><el-option value="仅本人"/><el-option value="可外发说明（需批准）"/></el-select><el-button type="primary" @click="annotation.trim()?ElMessage.success('已保存独立标注示意，未改写原片'):ElMessage.warning('请填写标注内容')">保存标注</el-button><p>工作批注默认不附在外链中，可回复、解决或撤回。</p><el-button @click="ElMessage.success('演示标注已标记解决')">标记解决</el-button></template>
</div></div></div>
<div v-else-if="page.special==='assistant'" class="chat-layout"><section class="surface chat-history"><h3>档案对话</h3><el-button @click="answer='';question='';answerState=''">＋ 新对话</el-button><button v-for="(m,i) in messages" :key="i" @click="ask(m)">{{m}}</button><p>仅本人可见 · 演示会话</p></section><section class="surface chat-main"><div class="editor-toolbar"><h3>有来源，才有答案</h3><el-select v-model="scope" style="width:280px"><el-option value="春江月 / 2026年 / 已确认资料"/><el-option value="全部已授权档案 / 当前版本"/></el-select></div><el-alert title="本页为固定示例问答，不调用AI服务，也不查询真实档案。" :closable="false"/><div v-if="!answer" class="chat-empty"><span class="chat-mark">藏</span><h2>你想从档案中了解什么？</h2><p>选择范围，再查证据；不会自动联网补充院团事实。</p><button v-for="q in ['广州首演的实际主角及录像版本？','两份记录的时长为什么不同，是否冲突？','是否有未登记的获奖记录？']" :key="q" @click="ask(q)">{{q}} →</button></div><div v-else class="answer-card"><el-tag :type="answerState==='有依据'?'success':'warning'">{{answerState}} · 演示</el-tag><h3>{{question}}</h3><p>{{answer}}</p><div v-if="answerState!=='证据不足'" class="citations"><button @click="sourceOpen=true">[1] 场次快照V2 · 实际阵容</button><button @click="sourceOpen=true">[2] 录像版本记录 · V2 / V3</button></div><small>范围：{{scope}} · 数据截止2026-10-09 · 未读取范围不作推断</small><div class="panel-actions"><el-select v-model="feedback" placeholder="反馈类型" style="width:150px"><el-option v-for="f in ['引用错误','事实错误','结果不相关','权限问题']" :key="f" :value="f"/></el-select><el-button @click="feedback?ElMessage.success('已记录演示反馈'):ElMessage.warning('请选择反馈类型')">提交反馈</el-button></div></div><form class="chat-input" @submit.prevent="ask()"><el-input v-model="question" placeholder="询问已授权档案中的事实…" aria-label="档案问题"/><el-button type="primary" native-type="submit" :loading="answerLoading">查看示例回答</el-button></form></section><el-dialog v-model="sourceOpen" title="引用证据 · 源版本核对" width="min(650px,95vw)"><el-tag>人工确认的演示记录</el-tag><h3>春江月 · 广州首演 · 快照V2</h3><p>演出日期：2026-10-08；实际主角：演员乙；确认人：刘执行。</p><p>来源入口在实际功能阶段将重新检查权限。当前仅展示虚构证据。</p><el-button @click="emit('navigate','events')">查看场次界面</el-button></el-dialog></div>
<div v-else-if="page.special==='similar'" class="surface similar-workspace"><div class="surface-title"><div><h3>谢幕连拍 · 候选组03</h3><span>仅限广州首演 / 不做人脸身份识别</span></div><el-button @click="split=!split;ElMessage.success(split?'已拆分演示候选组':'已恢复候选组示意')">{{split?'恢复分组示意':'拆分错误分组'}}</el-button></div><el-alert title="视觉相似不等于重复；代表图只改变展示，不删除原件或继承权利。" :closable="false"/><div class="similar-grid"><div v-for="i in split?[1]:[1,2,3]" :key="i" class="photo-compare"><div class="stage-photo" :class="'photo-'+i" :style="{backgroundSize:compareZoom+'%'}"><div class="photo-light"></div><span>谢幕光影<br><small>舞台示意素材 {{i}}</small></span></div><div><el-checkbox v-model="selectedPhotos" :value="i">{{i===1?'代表图候选':'保留为独立用途'}}</el-checkbox><p>照片0{{i}}.jpg · {{i===2?'裁剪版':'原始比例'}}</p><p>{{i===2?'3000 × 2000':'6000 × 4000'}} · 2026-10-08 21:40</p><el-tag :type="i===3?'warning':'success'">{{i===3?'已有分享引用':'宣传权利已确认'}}</el-tag></div></div></div><div class="panel-actions"><span>同步放大</span><el-slider v-model="compareZoom" :min="100" :max="180" style="width:220px"/><el-input v-model="photoReason" placeholder="保留原因" style="max-width:300px"/><el-button type="primary" @click="selectedPhotos.length?ElMessage.success('已将所选示意照片加入演示精选集'):ElMessage.warning('请先选择照片')">加入精选集</el-button><el-button @click="emit('navigate','recycle')">查看引用保护与回收</el-button></div></div>
</template>
