<script setup lang="ts">
import {ref,onMounted,watch} from 'vue'
import {ElMessage} from 'element-plus'
import {api,all} from './api'
const props=defineProps<{accounts:boolean,user:any,productions:any[]}>()
const rows=ref<any[]>([]),form=ref<any>({}),open=ref(false),busy=ref(false)
const roles:any={admin:'管理员',archivist:'档案管理员',business:'业务人员',finance:'财务人员',viewer:'普通查看',external:'外部接收人'}
async function run(fn:()=>Promise<void>){busy.value=true;try{await fn()}catch(e){ElMessage.error((e as Error).message)}finally{busy.value=false}}
async function load(){rows.value=await all(props.accounts?'accounts/':'people/')}
onMounted(()=>run(load));watch(()=>props.accounts,()=>{open.value=false;run(load)})
function edit(row?:any){form.value=row?{...row,productions:[...(row.productions??[])],password:''}:props.accounts?{username:'',password:'',role:'external',productions:[],is_active:true}:{name:'',specialty:'',biography:''};open.value=true}
function save(){run(async()=>{const data={...form.value};if(!data.password)delete data.password;delete data.id;await api((props.accounts?'accounts/':'people/')+(form.value.id?form.value.id+'/':''),data,false,form.value.id?'PATCH':'POST');open.value=false;await load();ElMessage.success('已保存')})}
</script>
<template>
<div v-loading="busy"><p class="muted">{{accounts?'岗位决定操作权限，授权剧目决定可访问范围；外部接收人仅能使用指定分享链接。':'演职人员档案与登录账号分开管理。此处只记录工作相关的公开基本信息。'}}</p><el-button v-if="accounts||['admin','archivist','business'].includes(user.role)" type="primary" @click="edit()">{{accounts?'新建账号':'新建人员'}}</el-button>
<el-table :data="rows"><template v-if="accounts"><el-table-column prop="username" label="账号"/><el-table-column label="岗位"><template #default="{row}">{{roles[row.role]}}</template></el-table-column><el-table-column label="授权剧目"><template #default="{row}">{{row.role==='admin'?'全部':row.productions.map((id:number)=>productions.find(p=>p.id===id)?.title??id).join('、')||'未分配'}}</template></el-table-column><el-table-column label="状态"><template #default="{row}">{{row.is_active?'启用':'停用'}}</template></el-table-column></template><template v-else><el-table-column prop="name" label="姓名"/><el-table-column prop="specialty" label="专业 / 职务"/><el-table-column prop="biography" label="工作简介"/></template><el-table-column label="操作"><template #default="{row}"><el-button v-if="row.role!=='admin'&&(accounts||['admin','archivist','business'].includes(user.role))" link type="primary" @click="edit(row)">编辑</el-button></template></el-table-column></el-table>
<el-dialog v-model="open" :title="(form.id?'编辑':'新建')+(accounts?'账号':'人员')" width="min(560px,94vw)"><el-form label-position="top" @submit.prevent="save"><template v-if="accounts"><el-form-item label="账号名称"><el-input aria-label="账号名称" v-model="form.username" :disabled="!!form.id" autocomplete="off"/></el-form-item><el-form-item :label="form.id?'新密码（留空保持原密码）':'初始密码'"><el-input v-model="form.password" type="password" autocomplete="new-password" show-password/></el-form-item><el-form-item label="岗位"><el-select v-model="form.role"><el-option v-for="r in ['archivist','business','finance','viewer','external']" :key="r" :label="roles[r]" :value="r"/></el-select></el-form-item><el-form-item label="授权剧目"><el-select v-model="form.productions" multiple filterable :disabled="form.role==='external'"><el-option v-for="p in productions" :key="p.id" :label="p.title" :value="p.id"/></el-select></el-form-item><el-switch v-model="form.is_active" active-text="启用账号"/><p class="muted">停用账号或收回分享者的相关权限后，现有分享将不可访问。</p></template><template v-else><el-form-item label="姓名"><el-input aria-label="人员姓名" v-model="form.name"/></el-form-item><el-form-item label="专业 / 职务"><el-input v-model="form.specialty"/></el-form-item><el-form-item label="工作简介"><el-input type="textarea" v-model="form.biography"/></el-form-item></template><el-button native-type="submit" type="primary" :loading="busy">保存</el-button></el-form></el-dialog></div>
</template>
