import { test, expect, type Page } from '@playwright/test'
async function login(page: Page, username: string) {
  await page.getByRole('textbox', {name:'账号', exact:true}).fill(username)
  await page.getByRole('textbox', {name:'密码', exact:true}).fill('Browser-Test-Only-42!')
  await page.getByRole('button', {name:'登录', exact:true}).click()
}
test('真实浏览器：建档、上传、检索、接收人分享与撤销', async ({page, browser}) => {
  await page.goto('/')
  await login(page, 'e2e_staff')
  await page.getByRole('button', {name:'剧目档案', exact:true}).click()
  await page.getByRole('button', {name:'＋ 新建剧目'}).click()
  let dialog=page.getByRole('dialog')
  await dialog.getByRole('textbox').nth(0).fill('浏览器试演剧目')
  await dialog.getByRole('textbox').nth(1).fill('话剧')
  await dialog.getByRole('button', {name:'保存', exact:true}).click()
  await expect(page.getByRole('cell', {name:'浏览器试演剧目', exact:true})).toBeVisible()
  await page.getByRole('button', {name:'演出场次', exact:true}).click()
  await page.getByRole('button', {name:'＋ 新建场次'}).click()
  dialog=page.getByRole('dialog')
  await dialog.locator('.el-select').first().click()
  await page.getByRole('option', {name:'浏览器试演剧目'}).click()
  await dialog.getByRole('textbox', {name:'场次名称',exact:true}).fill('首演夜场')
  await dialog.getByRole('combobox', {name:'演出时间',exact:true}).fill('2026-10-10 19:30:00')
  await dialog.getByRole('textbox', {name:'地点',exact:true}).fill('实验剧场')
  await dialog.getByRole('button', {name:'保存',exact:true}).click()
  await expect(page.getByRole('cell', {name:'首演夜场',exact:true})).toBeVisible()
  await page.getByRole('button', {name:'资料库',exact:true}).click()
  await page.getByRole('button', {name:'＋ 上传资料'}).click()
  dialog=page.getByRole('dialog')
  await dialog.locator('.el-select').first().click()
  await page.getByRole('option', {name:'浏览器试演剧目 / 首演夜场'}).click()
  await dialog.locator('input[type=file]').setInputFiles({name:'排练剧本.pdf', mimeType:'application/pdf', buffer:Buffer.from('%PDF-1.4\nBrowser fixture\n%%EOF')})
  await dialog.getByRole('button', {name:'保存',exact:true}).click()
  await expect(page.getByRole('cell', {name:'排练剧本.pdf',exact:true})).toBeVisible()
  await page.getByPlaceholder('搜索资料名、剧目或场次').fill('不存在的文件')
  await page.getByRole('button', {name:'检索',exact:true}).click()
  await expect(page.getByRole('cell', {name:'排练剧本.pdf',exact:true})).toHaveCount(0)
  await page.getByPlaceholder('搜索资料名、剧目或场次').fill('首演')
  await page.getByRole('button', {name:'检索',exact:true}).click()
  await page.getByRole('button', {name:'分享',exact:true}).click()
  dialog=page.getByRole('dialog')
  await dialog.getByRole('textbox', {name:'接收账号',exact:true}).fill('e2e_guest')
  await dialog.getByRole('button', {name:'生成分享链接'}).click()
  const link=await dialog.locator('input[readonly]').last().inputValue()
  expect(link).toContain('/share/')
  const guest=await browser.newContext()
  const guestPage=await guest.newPage()
  await guestPage.goto(link)
  await login(guestPage,'e2e_guest')
  await expect(guestPage.getByRole('heading', {name:'排练剧本.pdf'})).toBeVisible()
  await expect(guestPage.getByRole('link', {name:'下载文件'})).toHaveCount(0)
  const previewURL=await guestPage.getByRole('link', {name:'打开预览'}).getAttribute('href')
  const preview=await guestPage.request.get('http://127.0.0.1:5173'+previewURL)
  expect(preview.status()).toBe(200)
  expect(preview.headers()['content-type']).toBe('application/pdf')
  await dialog.getByRole('button', {name:'关闭',exact:true}).click()
  await page.getByRole('button', {name:'对外分享',exact:true}).click()
  await page.getByRole('button', {name:'撤销',exact:true}).click()
  await page.getByRole('button', {name:'确定',exact:true}).click()
  await expect(page.getByText('已撤销', {exact:true})).toBeVisible()
  await guestPage.reload()
  await expect(guestPage.getByText('分享不可用、已失效，或当前账号不是指定接收人')).toBeVisible()
  await guest.close()
  await page.screenshot({path:'test-results/workspace.png', fullPage:true})
})

test('档案增量：制作版本、阵容、历史文件及账号权限', async ({page,browser})=>{
  await page.goto('/');await login(page,'e2e_admin')
  await expect(page.getByRole('button',{name:'账号权限',exact:true})).toBeVisible()
  await page.evaluate(async()=>{
    const csrf=(await (await fetch('/api/session/')).json()).csrfToken
    async function post(path:string,data:any){const r=await fetch('/api/'+path+'/',{method:'POST',headers:{'Content-Type':'application/json','X-CSRFToken':csrf},body:JSON.stringify(data)});if(!r.ok)throw new Error(await r.text());return r.json()}
    const p=await post('productions',{title:'版本验证剧目',genre:'话剧'})
    await post('performances',{production:p.id,title:'版本验证场次',venue:'试验剧场',starts_at:'2026-10-11T19:30:00+08:00'})
  })
  await page.reload()
  await page.getByRole('button',{name:'剧目档案',exact:true}).click()
  await page.getByRole('row').filter({hasText:'版本验证剧目'}).getByRole('button',{name:'详情'}).click()
  let drawer=page.getByRole('dialog',{name:'档案详情'})
  await drawer.getByRole('textbox',{name:'新版本名称',exact:true}).fill('复排版')
  await drawer.getByRole('button',{name:'新增制作版本'}).click()
  await expect(drawer.getByRole('textbox',{name:'制作版本名称',exact:true})).toHaveCount(2)
  await drawer.locator('.el-select').filter({has:page.getByRole('combobox',{name:'角色所属版本'})}).click()
  await page.getByRole('option',{name:'默认版',exact:true}).click()
  await drawer.getByRole('textbox',{name:'角色名称',exact:true}).fill('主角')
  await drawer.getByRole('button',{name:'新增角色',exact:true}).click()
  await expect(drawer.getByRole('button',{name:'保存角色'})).toHaveCount(1)
  await drawer.locator('.el-drawer__close-btn').click()
  await page.getByRole('button',{name:'演职人员',exact:true}).click()
  await page.getByRole('button',{name:'新建人员',exact:true}).click()
  let dialog=page.getByRole('dialog')
  await dialog.getByRole('textbox',{name:'人员姓名',exact:true}).fill('演示演员')
  await dialog.getByRole('button',{name:'保存',exact:true}).click()
  await expect(page.getByRole('cell',{name:'演示演员',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'演出场次',exact:true}).click()
  await page.getByRole('row').filter({hasText:'版本验证场次'}).getByRole('button',{name:'详情'}).click()
  drawer=page.getByRole('dialog',{name:'档案详情'})
  await drawer.locator('.el-select').filter({has:page.getByRole('combobox',{name:'阵容人员'})}).click()
  await page.getByRole('option',{name:'演示演员 /'}).click()
  await drawer.locator('.el-select').filter({has:page.getByRole('combobox',{name:'阵容角色'})}).click()
  await page.getByRole('option',{name:'主角',exact:true}).click()
  await drawer.getByRole('button',{name:'添加阵容记录'}).click()
  await expect(drawer.getByRole('button',{name:'保存阵容'})).toHaveCount(1)
  await drawer.locator('label.el-radio').filter({hasText:'计划阵容'}).click()
  await drawer.getByRole('button',{name:'添加阵容记录'}).click()
  await expect(drawer.getByRole('button',{name:'保存阵容'})).toHaveCount(2)
  await page.screenshot({path:'test-results/cast.png',fullPage:true})
  await drawer.locator('.el-drawer__close-btn').click()
  await page.getByRole('button',{name:'资料库',exact:true}).click()
  await page.getByRole('button',{name:'＋ 上传资料'}).click()
  dialog=page.getByRole('dialog')
  await dialog.locator('.el-select').first().click()
  await page.getByRole('option',{name:'版本验证剧目 / 版本验证场次'}).click()
  await dialog.locator('input[type=file]').setInputFiles({name:'历史文件.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-Old version')})
  await dialog.getByRole('button',{name:'保存',exact:true}).click()
  const row=page.getByRole('row').filter({hasText:'历史文件.pdf'})
  await row.getByRole('button',{name:'分享',exact:true}).click()
  dialog=page.getByRole('dialog')
  await dialog.getByRole('textbox',{name:'接收账号'}).fill('e2e_guest')
  await dialog.getByRole('button',{name:'生成分享链接'}).click()
  const link=await dialog.locator('input[readonly]').last().inputValue()
  await dialog.getByRole('button',{name:'关闭',exact:true}).click()
  await row.getByRole('button',{name:'详情'}).click()
  drawer=page.getByRole('dialog',{name:'档案详情'})
  await drawer.getByRole('textbox',{name:'版本说明'}).fill('第二稿修订')
  await drawer.locator('input[type=file]').setInputFiles({name:'第二稿.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-New version')})
  await drawer.getByRole('button',{name:'上传新版本',exact:true}).click()
  await expect(drawer.getByRole('heading',{name:'文件历史版本 · 当前 V2'})).toBeVisible()
  await page.screenshot({path:'test-results/versions.png',fullPage:true})
  const guest=await browser.newContext();const guestPage=await guest.newPage()
  await guestPage.goto(link);await login(guestPage,'e2e_guest')
  await expect(guestPage.getByRole('heading',{name:'历史文件.pdf'})).toBeVisible()
  const url=await guestPage.getByRole('link',{name:'打开预览'}).getAttribute('href')
  expect(await (await guestPage.request.get('http://127.0.0.1:5173'+url)).text()).toBe('%PDF-Old version')
  await guest.close()
  await drawer.locator('.el-drawer__close-btn').click()
  await page.getByRole('button',{name:'账号权限',exact:true}).click()
  await page.getByRole('button',{name:'新建账号',exact:true}).click()
  dialog=page.getByRole('dialog')
  await dialog.getByRole('textbox',{name:'账号名称'}).fill('new_recipient')
  await dialog.locator('input[type=password]').fill('Strong-Recipient-42!')
  await dialog.getByRole('button',{name:'保存',exact:true}).click()
  await expect(page.getByRole('cell',{name:'new_recipient',exact:true})).toBeVisible()
  await page.screenshot({path:'test-results/accounts.png',fullPage:true})
})
