import { test, expect, type Page } from '@playwright/test'
async function login(page: Page, username: string) {
  await page.getByRole('textbox', {name:'账号', exact:true}).fill(username)
  await page.getByRole('textbox', {name:'密码', exact:true}).fill('Browser-Test-Only-42!')
  await page.getByRole('button', {name:'登录', exact:true}).click()
}
test('真实浏览器：建档、上传、检索、接收人分享与撤销', async ({page, browser}) => {
  await page.goto('/')
  await login(page, 'e2e_staff')
  await page.getByRole('button', {name:'剧目档案', exact:true}).click()
  await page.getByRole('button', {name:'＋ 新建剧目'}).click()
  let dialog=page.getByRole('dialog')
  await dialog.getByRole('textbox').nth(0).fill('浏览器试演剧目')
  await dialog.getByRole('textbox').nth(1).fill('话剧')
  await dialog.getByRole('button', {name:'保存', exact:true}).click()
  await expect(page.getByRole('cell', {name:'浏览器试演剧目', exact:true})).toBeVisible()
  await page.getByRole('button', {name:'演出场次', exact:true}).click()
  await page.getByRole('button', {name:'＋ 新建场次'}).click()
  dialog=page.getByRole('dialog')
  await dialog.getByRole('combobox').nth(0).click()
  await page.getByRole('option', {name:'浏览器试演剧目'}).click()
  await dialog.getByRole('textbox', {name:'场次名称',exact:true}).fill('首演夜场')
  await dialog.getByRole('combobox', {name:'演出时间',exact:true}).fill('2026-10-10 19:30:00')
  await dialog.getByRole('textbox', {name:'地点',exact:true}).fill('实验剧场')
  await dialog.getByRole('button', {name:'保存',exact:true}).click()
  await expect(page.getByRole('cell', {name:'首演夜场',exact:true})).toBeVisible()
  await page.getByRole('button', {name:'资料库',exact:true}).click()
  await page.getByRole('button', {name:'＋ 上传资料'}).click()
  dialog=page.getByRole('dialog')
  await dialog.getByRole('combobox').nth(0).click()
  await page.getByRole('option', {name:'浏览器试演剧目 / 首演夜场'}).click()
  await dialog.locator('input[type=file]').setInputFiles({name:'排练剧本.pdf', mimeType:'application/pdf', buffer:Buffer.from('%PDF-1.4\nBrowser fixture\n%%EOF')})
  await dialog.getByRole('button', {name:'保存',exact:true}).click()
  await expect(page.getByRole('cell', {name:'排练剧本.pdf',exact:true})).toBeVisible()
  await page.getByPlaceholder('搜索资料名、剧目或场次').fill('不存在的文件')
  await page.getByRole('button', {name:'检索',exact:true}).click()
  await expect(page.getByRole('cell', {name:'排练剧本.pdf',exact:true})).toHaveCount(0)
  await page.getByPlaceholder('搜索资料名、剧目或场次').fill('首演')
  await page.getByRole('button', {name:'检索',exact:true}).click()
  await page.getByRole('button', {name:'分享',exact:true}).click()
  dialog=page.getByRole('dialog')
  await dialog.getByRole('textbox', {name:'接收账号',exact:true}).fill('e2e_guest')
  await dialog.getByRole('button', {name:'生成分享链接'}).click()
  const link=await dialog.locator('input[readonly]').last().inputValue()
  expect(link).toContain('/share/')
  const guest=await browser.newContext()
  const guestPage=await guest.newPage()
  await guestPage.goto(link)
  await login(guestPage,'e2e_guest')
  await expect(guestPage.getByRole('heading', {name:'排练剧本.pdf'})).toBeVisible()
  await expect(guestPage.getByRole('link', {name:'下载文件'})).toHaveCount(0)
  const previewURL=await guestPage.getByRole('link', {name:'打开预览'}).getAttribute('href')
  const preview=await guestPage.request.get('http://127.0.0.1:5173'+previewURL)
  expect(preview.status()).toBe(200)
  expect(preview.headers()['content-type']).toBe('application/pdf')
  await dialog.getByRole('button', {name:'关闭',exact:true}).click()
  await page.getByRole('button', {name:'对外分享',exact:true}).click()
  await page.getByRole('button', {name:'撤销',exact:true}).click()
  await page.getByRole('button', {name:'确定',exact:true}).click()
  await expect(page.getByText('已撤销', {exact:true})).toBeVisible()
  await guestPage.reload()
  await expect(guestPage.getByText('分享不可用、已失效，或当前账号不是指定接收人')).toBeVisible()
  await guest.close()
  await page.screenshot({path:'test-results/workspace.png', fullPage:true})
})
