# Generated by Django 5.2.18 on 2026-10-09 03:07

import archive.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('biography', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='financial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='production',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='share',
            name='title_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='AccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('archivist', '档案员'), ('business', '演出业务'), ('finance', '财务'), ('viewer', '普通查看'), ('external', '外部接收人')], default='external', max_length=20)),
                ('productions', models.ManyToManyField(blank=True, related_name='access_profiles', to='archive.production')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=archive.models.original_path)),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='archive.asset')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for', to='archive.assetversion'),
        ),
        migrations.AddField(
            model_name='share',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archive.assetversion'),
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='archive.production')),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performances', to='archive.edition'),
        ),
        migrations.CreateModel(
            name='StageRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('actor', '演员角色'), ('crew', '工作人员岗位')], default='actor', max_length=10)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_roles', to='archive.edition')),
            ],
        ),
        migrations.CreateModel(
            name='CastAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('planned', '计划'), ('actual', '实际')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cast', to='archive.performance')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='archive.person')),
                ('stage_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.stagerole')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assetversion',
            constraint=models.UniqueConstraint(fields=('asset', 'number'), name='asset_version_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='edition',
            constraint=models.UniqueConstraint(fields=('production', 'name'), name='edition_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='stagerole',
            constraint=models.UniqueConstraint(fields=('edition', 'name', 'kind'), name='stage_role_unique'),
        ),
        migrations.AddConstraint(
            model_name='castassignment',
            constraint=models.UniqueConstraint(fields=('performance', 'person', 'stage_role', 'phase'), name='cast_assignment_unique'),
        ),
    ]
